### ISSUE TITLE
Raster.rename creates extra names

### ISSUE THREAD

**Issue by aazuspan** [stevenpawley/Pyspatialml#32] opened 2021-08-11 22:48 UTC
Hi @stevenpawley,

I came across some strange behavior in the `Raster.rename` method. If you attempt to rename the bands of a Raster, extra default band names will be created. In other words, if you rename 3 bands, you'll end up with 9 bands: 3 correctly named bands and 6 new bands.

```python
import rasterio, pyspatialml, numpy as np

# Create a fake 3-band image for testing
arr = np.random.rand(3, 64, 64)
with rasterio.open("test.tif", "w", width=64, height=64, count=3, dtype=np.float32) as dst:
    dst.write(arr)
    
r = pyspatialml.Raster("test.tif")

renamed = r.rename(dict(zip(r.names, ["Red", "Green", "Blue"])))
```

```python
>>> r.names
['test_1', 'test_2', 'test_3']

>>> renamed.names
['Red', 'Green', 'Blue', 'test_4', 'test_5', 'test_6', 'test_7', 'test_8', 'test_9']
```

I'm running the latest Pyspatialml installed from Github.

**Comment by stevenpawley** [comment] 2021-08-19 01:11
Thanks for reporting this; probably an issue caused by some recent refactoring.

**Comment by stevenpawley** [comment] 2021-08-22 16:50
Should be fixed now, thanks for reporting this

**Closed by stevenpawley** 2021-08-22 16:50 UTC
